### ISSUE TITLE
dl2 and dl10 not working

### ISSUE THREAD

**Issue by bathiya** [saturn99/open-film-server#24]
http://dl2.sermovie.xyz/ and http://dl10.sermovie.xyz/ not working
**_404 - File or directory not found_**
Any fix for this or a new link?

**Comment by saturn99** [comment]
dl2 ? where is dl2 ? 

dl10  fixed at db51abd71bc81cf8f303d15b71767d09354c6c45

**Comment by bathiya** [comment]
dl10 is also giving a 404 error. looks like the server is offline

**Comment by saturn99** [comment]
> dl10 is also giving a 404 error. looks like the server is offline

dl10 is fixed re check it 
https://saturn99.github.io/open-film-server/dl10.sermovie.xyz/
